### ISSUE TITLE
agent 配置到 transfer的 HA  失效

### ISSUE THREAD

**Issue by xinghui-hou** [open-falcon-archive/agent#43]
agent 连接transfer 的配置文件里填了两个ip
![7j4axuu ql36gbv p7bvxa](https://cloud.githubusercontent.com/assets/10824788/14200371/1f0222c4-f81d-11e5-8243-826902b40f32.jpg)
其中一个挂了之后就无法访问了
![1 mp 6fp 0zs ci_5 y9n1y](https://cloud.githubusercontent.com/assets/10824788/14200372/21650a54-f81d-11e5-84f1-fb83192a81aa.jpg)

**Comment by laiwei** [comment]
https://github.com/open-falcon/agent/pull/37

**Comment by walnut-tom** [comment]
ip 地址还是漏出来了

**Comment by laiwei** [comment]
https://github.com/open-falcon/falcon-plus/commit/cc1f7069c746fe1925dc42c136d360f59c3e895d

fixed:)
