### ISSUE TITLE
agent可能出现concurrent map read and write错误

### ISSUE THREAD

**Issue by aprilnops** [open-falcon-archive/agent#70]
agent/g/transfer.go第21-23行：
`
if _, ok := TransferClients[addr]; !ok {
`
`
initTransferClient(addr)(url)
`
`
}
`
存在着同时执行`TransferClients[addr]`和`initTransferClient(addr)(url)`的隐患（即使从程序逻辑上看不会同时执行），initTransferClient中加了写锁，而TransferClients[addr]是直接读取map没有加读锁，因此可能出现同时读写map的错误

**Comment by ylywyn** [comment]
+1

**Comment by ylywyn** [comment]
没有人维护了吗？？？

`
fatal error: concurrent map read and map write
goroutine 30 [running]:
runtime.throw(0x7dfa50, 0x21)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4204add40 sp=0xc4204add20
runtime.mapaccess2_faststr(0x76b400, 0xc420166180, 0xc42010d3c0, 0x13, 0xc4204ade08, 0x4e1490)
	/usr/local/go/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc4204adda0 sp=0xc4204add40
github.com/open-falcon/agent/g.SendMetrics(0xc42029e040, 0x6, 0x8, 0xc4203de1e0)
`

**Comment by laiwei** [comment]
@ylywyn 请帮忙贴全一点的日志哈

**Comment by ylywyn** [comment]
pull request 了

**Comment by laiwei** [comment]
@ylywyn  thanks

https://github.com/open-falcon/falcon-plus/commit/cc1f7069c746fe1925dc42c136d360f59c3e895d
