### ISSUE TITLE
transfer ha 问题

### ISSUE THREAD

**Issue by rkasdf** [open-falcon-archive/agent#83]
您好：
我看commits里已经解决了transfer的高可用问题， 我使用最新的代码编译的agent，发现仍然存在数据缺失问题，我停掉了两个transfer中的一个，数据上报间隔是30s。
我看到agent的日志里确实访问不到我停掉的transfer
请问这可能是由于什么造成的
![image](https://cloud.githubusercontent.com/assets/5036644/22196203/efe52cee-e186-11e6-947b-fcd227108d09.png)

**Comment by laiwei** [comment]
https://github.com/open-falcon/falcon-plus/commit/cc1f7069c746fe1925dc42c136d360f59c3e895d

看看这个是否解决了你的问题
